---
- name: ssl | Installing Python Modules
  pip:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'pyOpenSSL'

- name: ssl | Ensuring SSL Keys Folders Exist
  file:
    path: "{{ item|dirname }}"
    state: "directory"
  become: true
  with_items:
    - "{{ nginx_load_balancer_ssl['private_key_file'] }}"
    - "{{ nginx_load_balancer_ssl['public_key_file'] }}"
  when: nginx_load_balancer_ssl['generate_keys']

- name: ssl | Generating SSL Private Key
  openssl_privatekey:
    force: "{{ nginx_load_balancer_ssl['regenerate_keys'] }}"
    path: "{{ nginx_load_balancer_ssl['private_key_file'] }}"
    size: "{{ nginx_load_balancer_ssl['private_key_size'] }}"
    state: "present"
    type: "{{ nginx_load_balancer_ssl['private_key_type'] }}"
  become: true
  register: "_nginx_load_balancer_ssl_priv_key"
  when: nginx_load_balancer_ssl['generate_keys']

# This module is included in Ansible 2.4 so for now it is included in library/
- name: ssl | Generating SSL CSR
  openssl_csr:
    force: "{{ nginx_load_balancer_ssl['regenerate_keys'] }}"
    commonName: "{{ inventory_hostname }}"
    path: "{{ nginx_load_balancer_ssl['csr_key_file'] }}"
    privatekey_path: "{{ nginx_load_balancer_ssl['private_key_file'] }}"
  become: true
  register: "_nginx_load_balancer_ssl_csr"
  when: nginx_load_balancer_ssl['generate_keys']

# The below module does not work as expected
# - name: ssl | Generating SSL Public Key
#   openssl_publickey:
#     force: "{{ nginx_load_balancer_ssl['regenerate_keys'] }}"
#     path: "{{ nginx_load_balancer_ssl['public_key_file'] }}"
#     privatekey_path: "{{ nginx_load_balancer_ssl['private_key_file'] }}"
#     state: "present"
#   become: true
#   when: nginx_load_balancer_ssl['generate_keys']

- name: ssl | Generating SSL Public Key
  command: >
           openssl req
           -x509
           -days {{ nginx_load_balancer_ssl['public_key_valid_days'] }}
           -key {{ nginx_load_balancer_ssl['private_key_file'] }}
           -in {{nginx_load_balancer_ssl['csr_key_file'] }}
           -out {{ nginx_load_balancer_ssl['public_key_file'] }}
  become: true
  when: >
        nginx_load_balancer_ssl['generate_keys'] and
        (_nginx_load_balancer_ssl_priv_key['changed'] or
        _nginx_load_balancer_ssl_csr['changed'])
