---
- name: Converge
  hosts: all
  vars:
    nginx_load_balancer_configs:
      - name: google_dns
        frontend_listen_port: 53
        method: round_robin
        protocol: udp
        upstream:
          - server: 8.8.8.8
            backend_listen_port: 53
          - server: 8.8.4.4
            backend_listen_port: 53
    nginx_load_balancer_ssl:
      {}
      # csr_key_file: "/etc/ssl/{{ inventory_hostname }}-csr.pem"
      # enabled: false
      # generate_keys: false
      # private_key_file: "/etc/ssl/private/{{ inventory_hostname }}-key.pem"
      # private_key_size: 4096
      # private_key_type: RSA
      # protocols:
      #   - TLSv1
      #   - TLSv1.1
      #   - TLSv1.2
      # public_key_file: "/etc/ssl/public/{{ inventory_hostname }}-cert.pem"
      # public_key_valid_days: 1825
      # regenerate_keys: false
  tasks:
    - name: Include ansible-nginx-load-balancer
      include_role:
        name: ansible-nginx-load-balancer
